### ISSUE TITLE
[NSFW] napiszar. com

### ISSUE THREAD

**Issue by PerfectSalad** [hufilter/hufilter#8]
popunder / popunder or idk code

Should `napiszar.com##+js(acis, D4zz)` be added?

**Comment by scripthunter7** [comment]
@PerfectSalad I don't think it's a good idea to abort this script based on this name, because it's generated by an obfuscator.

In Firefox, uBO can filter out completely these scripts from HTML code at network level by this rule:
```
napiszar.com##^script[data-cfasync]
```

For Chrome browsers, you can block it based on document.createElement and setTimeout:
```
napiszar.com##+js(acis, document.createElement, setTimeout)
```
